model_dir: /home/vsatish/Data/dexnet/data/models/suction
output_dir: /mnt/hdd/dex-net/data/analyses/gqcnn_training_performance

out_rate: 1
font_size: 15
dpi: 100

models:
  mini_dexnet_09_05_17:
    tag: GQCNN (N=100)
    type: gqcnn
    split_type: image_wise # valid split-types are image_wise, object_wise, image_stable_pose_wise
    batch_size: 64
    im_height: 32
    im_width: 32
    im_channels: 1
    input_data_mode: tf_image_suction
    replace: 0
    vis_conv: 0
